load("@rules_rust//rust:rust_binary.bzl", "rust_binary")
load("@rules_rust//rust:rust_test.bzl", "rust_test")

exports_files([
    "Cargo.toml",
    "Cargo.lock",
])

rust_binary(
    name = "collect_ada_coverage",
    srcs = ["main.rs"],
    edition = "2021",
    visibility = ["//visibility:public"],
    deps = [
        "@racov//:flate2",
        "@racov//:serde",
        "@racov//:serde_json",
        "@racov//:walkdir",
        "@rules_rust//rust/runfiles",
    ],
)

rust_test(
    name = "collect_ada_coverage_test",
    crate = ":collect_ada_coverage",
)
